name: Publish Experimental Packages

on:
  push:
    branches:
      - main

jobs:
  publish-experimental:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish Experimental Package
        uses: colodenn/github-actions/.github/actions/bump-version/action.yml@main
        with:
          package_dir: './'  # Adjust this path if your package is not at the root
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}