# File: .github/workflows/publish-experimental.yml

name: Publish Experimental Packages

on:
  pull_request:
    branches:
      - main

jobs:
  publish-experimental:
    uses: colodenn/github-actions/.github/workflows/publish-experimental.yml@main
    with:
      package_dir: './'  # Adjust this path if your package is not at the root
    secrets:
      NPM_TOKEN_READ_AND_WRITE: ${{ secrets.NPM_TOKEN_READ_AND_WRITE }}