# File: .github/workflows/manual-publish.yml

name: Manually Publish npm Packages

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type to bump the package version by.'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease

jobs:
  publish:
    uses: colodenn/github-actions/.github/workflows/publish-manually.yml@main
    with:
      version_type: ${{ inputs.version_type }}
      package_dir: './'  # Adjust if your package is in a subdirectory
    secrets:
      NPM_TOKEN_READ_AND_WRITE: ${{ secrets.NPM_TOKEN_READ_AND_WRITE }}
      # TODO CHANGE THIS BACK TO RONIN_ORG_APP_ID
      ORG_GH_APP_ID: ${{ secrets.APP_ID }}
      ORG_GH_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}